# Generated by Django 6.1.1 on 2026-09-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSingUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_picture')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('user_status', models.CharField(choices=[('user_comum', 'usuario comum, ainda sem pagar'), ('beta_test', 'usuario de testes'), ('user_vip', 'usuario vip')], default='user_comum', max_length=20)),
            ],
        ),
    ]
