# Generated by Django 5.2.7 on 2025-10-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gender",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movie", models.FileField(blank=True, null=True, upload_to="movies")),
                ("name_movie", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("poster", models.ImageField(upload_to="posters")),
                ("release_date", models.DateField(blank=True, null=True)),
                ("watch_count", models.PositiveIntegerField(default=0)),
                ("gender", models.ManyToManyField(to="home.gender")),
            ],
        ),
    ]
