# Generated by Django 5.2.7 on 2025-10-30 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movies",
            name="gender",
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
        migrations.DeleteModel(
            name="Movies",
        ),
    ]
