# Generated by Django 5.2.7 on 2025-10-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0002_codigoemail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="telefone",
            field=models.CharField(max_length=20),
        ),
    ]
