# Generated by Django 5.2.7 on 2025-10-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cadastro", "0003_alter_customuser_telefone"),
    ]

    operations = [
        migrations.CreateModel(
            name="Codigo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Codigo_Selecionado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telefone", models.CharField(max_length=11)),
                ("email", models.EmailField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="CodigoEmail",
        ),
        migrations.DeleteModel(
            name="CodigoSMS",
        ),
        migrations.AddField(
            model_name="codigo",
            name="resultado",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cadastro.codigo_selecionado",
            ),
        ),
    ]
