# Generated by Django 5.2.10 on 2026-02-11 18:42

import datetime
import django.db.models.deletion
import filmes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status_movie",
                    models.CharField(
                        choices=[
                            ("terminado", "Terminado"),
                            ("ainda_lancando", "ainda lançando"),
                            ("em_breve", "Em breve"),
                            ("disponivel", "disponivel"),
                        ]
                    ),
                ),
                (
                    "gener_movie",
                    models.CharField(
                        blank=True,
                        choices=[("sem_genero", "sem genero"), ("romance", "romance")],
                        null=True,
                    ),
                ),
                (
                    "file_movie",
                    models.FileField(upload_to=filmes.models.get_source_file_path),
                ),
                ("hls_file", models.CharField(blank=True, max_length=500, null=True)),
                ("sprite_vtt", models.CharField(blank=True, max_length=500, null=True)),
                ("duration_all", models.DurationField(blank=True, null=True)),
                ("current_time", models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name="Series",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_serie", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status_series",
                    models.CharField(
                        choices=[
                            ("terminado", "Terminado"),
                            ("ainda_lancando", "ainda lançando"),
                            ("em_breve", "Em breve"),
                            ("disponivel", "disponivel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gener_serie",
                    models.CharField(
                        blank=True,
                        choices=[("sem_genero", "sem genero"), ("romance", "romance")],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MoviesWatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Visualização"
                    ),
                ),
                (
                    "movie_watched",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filmes.movies",
                        verbose_name="Filme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_episode", models.CharField(max_length=200)),
                ("season_number", models.PositiveIntegerField(default=1)),
                ("episode_number", models.PositiveIntegerField()),
                ("hls_file", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "file_episode",
                    models.FileField(upload_to=filmes.models.get_source_file_path),
                ),
                ("sprite_vtt", models.CharField(blank=True, max_length=500, null=True)),
                ("duration_all", models.DurationField(blank=True, null=True)),
                ("current_time", models.DurationField(default=datetime.timedelta(0))),
                (
                    "series",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="filmes.series",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VideoSprite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.FloatField(verbose_name="Início (s)")),
                ("end_time", models.FloatField(verbose_name="Fim (s)")),
                (
                    "interval",
                    models.PositiveIntegerField(default=10, verbose_name="Intervalo"),
                ),
                (
                    "columns",
                    models.PositiveIntegerField(default=5, verbose_name="Colunas"),
                ),
                ("rows", models.PositiveIntegerField(default=1, verbose_name="Linhas")),
                (
                    "frame_width",
                    models.PositiveIntegerField(
                        default=160, verbose_name="Largura do Frame"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="sprites/%Y/%m/%d/", verbose_name="Imagem"
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprites",
                        to="filmes.episode",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprites",
                        to="filmes.movies",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sprite Sheet",
                "verbose_name_plural": "Sprite Sheets",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="EpisodeWatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Visualização"
                    ),
                ),
                (
                    "episode_watched",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filmes.episode",
                        verbose_name="Episódio Assistido",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "ordering": ["-watched_at"],
                "unique_together": {("user", "episode_watched")},
            },
        ),
    ]
