# Generated by Django 5.2.7 on 2025-11-23 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MoviesWatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Visualização"
                    ),
                ),
                (
                    "movie_watched",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filmes.movies",
                        verbose_name="Filme",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
    ]
