# Generated by Django 5.2.7 on 2026-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='watch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
