# Generated by Django 5.2.7 on 2025-11-23 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmes", "0002_movieswatched"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("season_number", models.PositiveIntegerField(default=1, unique=True)),
            ],
            options={
                "ordering": ["season_number"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("episode_number", models.PositiveIntegerField(default=1)),
                ("episode_title", models.CharField(max_length=200)),
                ("episode_video", models.FileField(upload_to="series_episodes")),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="filmes.season",
                    ),
                ),
            ],
            options={
                "ordering": ["episode_number"],
                "unique_together": {("season", "episode_number")},
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_serie", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                ("serie_poster", models.ImageField(upload_to="series_posters")),
                ("gender", models.ManyToManyField(to="filmes.gender")),
            ],
        ),
        migrations.AddField(
            model_name="season",
            name="serie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="filmes.serie",
            ),
        ),
        migrations.CreateModel(
            name="EpisodeWatched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "watched_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Visualização"
                    ),
                ),
                (
                    "episode_watched",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="filmes.episode",
                        verbose_name="Episódio Assistido",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "ordering": ["-watched_at"],
                "unique_together": {("user", "episode_watched")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("serie", "season_number")},
        ),
    ]
