# Generated by Django 5.2.7 on 2025-10-31 00:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("filmes", "0002_alter_gender_options_alter_movies_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movies",
            old_name="movie",
            new_name="video",
        ),
    ]
