# Generated by Django 5.2.7 on 2025-12-25 18:01

import filmes.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filmes", "0004_movies_poster_1200w_movies_poster_400w_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="episode_video",
            field=models.FileField(upload_to=filmes.models.path_episode_video),
        ),
        migrations.AlterField(
            model_name="movies",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=filmes.models.path_movie_video
            ),
        ),
    ]
