# Generated by Django 5.2.7 on 2026-01-07 19:29

import filmes.models
import upload.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0005_alter_episode_episode_video_alter_movies_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_video',
            field=upload.fields.S3FileField(upload_to=filmes.models.path_episode_video),
        ),
        migrations.AlterField(
            model_name='movies',
            name='video',
            field=upload.fields.S3FileField(blank=True, null=True, upload_to=filmes.models.path_movie_video),
        ),
    ]
