# Generated by Django 6.1.1 on 2026-09-12 21:00

import datetime
import django.db.models.deletion
import movies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_movie', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status_movie', models.CharField(choices=[('terminado', 'Terminado'), ('ainda_lancando', 'ainda lançando'), ('em_breve', 'Em breve'), ('disponivel', 'disponivel')])),
                ('gener_movie', models.CharField(blank=True, choices=[('sem_genero', 'sem genero'), ('romance', 'romance')], null=True)),
                ('file_movie', models.FileField(upload_to=movies.utils.get_source_file_path)),
                ('hls_file', models.CharField(blank=True, max_length=500, null=True)),
                ('duration_all', models.DurationField(blank=True, null=True)),
                ('current_time', models.DurationField(default=datetime.timedelta(0))),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_serie', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status_series', models.CharField(choices=[('terminado', 'Terminado'), ('ainda_lancando', 'ainda lançando'), ('em_breve', 'Em breve'), ('disponivel', 'disponivel')], max_length=20)),
                ('gener_serie', models.CharField(blank=True, choices=[('sem_genero', 'sem genero'), ('romance', 'romance')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MoviesWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Visualização')),
                ('movie_watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movies', verbose_name='Filme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.usersingup', verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_episode', models.CharField(max_length=200)),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('episode_number', models.PositiveIntegerField()),
                ('file_episode', models.FileField(upload_to=movies.utils.get_source_file_path)),
                ('duration_all', models.DurationField(blank=True, null=True)),
                ('current_time', models.DurationField(default=datetime.timedelta(0))),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.series')),
            ],
        ),
        migrations.CreateModel(
            name='EpisodeWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now=True, verbose_name='Última Visualização')),
                ('episode_watched', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.episode', verbose_name='Episódio Assistido')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.usersingup', verbose_name='Usuário')),
            ],
            options={
                'ordering': ['-watched_at'],
                'unique_together': {('user', 'episode_watched')},
            },
        ),
    ]
