# Generated by Django 6.1.1 on 2026-09-12 21:15

import movies.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='movie_cover',
            field=models.FileField(default=None, upload_to=movies.utils.get_source_file_path),
        ),
    ]
