# Generated by Django 6.1.1 on 2026-09-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movies_movie_cover'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='hls_file',
        ),
        migrations.AddField(
            model_name='movies',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to='movies/hls/'),
        ),
    ]
